
/CloudProcessor:
  ros__parameters:

    voxel_filter:
      leaf_size_xy: 0.04    
      leaf_size_z: 0.08     

    crop_box:
      min_x: 0.0
      max_x: 2.0
      min_y: -0.7
      max_y: 0.7
      min_z: -3.0
      max_z: 1.0

    topic_names:
      input_point_cloud_topic: "/zedm/zed_node/point_cloud/cloud_registered"
      filtered_point_cloud_topic: "/stair_modeling_ros/point_cloud/cloud_filtered"

    frame_ids:
      input_cloud_frame: "zedm_left_camera_frame"
      output_cloud_frame: "zedm_base_link_projected"

/StairModeling:
  ros__parameters:

    segmentation:
      distance_threshold: 0.05
      max_iterations: 500
      angle_threshold: 5.

    clustering:
      cluster_tolerance: 0.08
      min_cluster_size: 50
      max_cluster_size: 25000

    floor_finding:
      k_neighbors: 50

    avg_x_calculation:
      x_neighbors: 20
      y_threshold: 0.05

    topic_names:
      filtered_point_cloud_topic: "/stair_modeling_ros/point_cloud/cloud_filtered"

    frame_ids:
      output_cloud_frame: "zedm_base_link_projected"

/ZionBroadcaster:
  ros__parameters:

    frame_ids:
      map_frame: "map"
      base_frame: "zedm_base_link"
      input_cloud_frame: "zedm_left_camera_frame"
      output_cloud_frame: "zedm_base_link_projected"

/**:
    ros__parameters:
      allNodeCanSee: True