zion:
  stair_modeling:
    ros__parameters:

      voxel_filter:
        leaf_size_xy: 0.04    
        leaf_size_z: 0.08     

      crop_box:
        min_x: 0.0
        max_x: 2.0
        min_y: -0.7
        max_y: 0.7
        min_z: -3.0
        max_z: 1.0

      topic_names:
        input_point_cloud_topic: "/zedm/zed_node/point_cloud/cloud_registered"
        # input_point_cloud_topic: "/zedm/zed_node/mapping/fused_cloud"

        # input_point_cloud_topic: "/zion/stair_modeling/cloud_filtered"
      frame_ids:
        map_frame: "map"
        input_cloud_frame: "zedm_left_camera_frame"     # "zedm_left_camera_frame" when using the raw topic
                                                        # "map" when using the fused topic
        output_cloud_frame: "zedm_base_link_projected"  

      segmentation:
        distance_threshold: 0.04
        max_iterations: 600
        angle_threshold: 3.

      clustering:
        cluster_tolerance: 0.035
        min_cluster_size: 30
        max_cluster_size: 25000

      floor_finding:
        k_neighbors: 30

      avg_x_calculation:
        x_neighbors: 30
        y_threshold: 0.055


      stair_filter:
        filter_min_limit: 3  
        filter_max_limit: 20  # maximum counts that stair can get,can put as param
        pos_err_thresh: 0.06
        w: 0.8                # weight factor for update the stair value 
                              # stair = w * curr_stair + (1-w) * stair | 0.5 = avg

/**:
    ros__parameters:
      allNodeCanSee: True